server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://ec2-54-159-112-44.compute-1.amazonaws.com:5432/d39i5jhsnc9gm1
    username: dlxxstrwminvmv
    password: 131120aed2033cc032ae270b71cbabcdb7b36477c494e3da9691041ef741ee24
  mail:
    host: smtp.gmail.com
    port: 587
    username: gasimzade09@gmail.com
    password: 789643
    #    username: ******
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    database: postgresql
    properties:
      #      DISABLE JPA VERSION EXCEPTION
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
jwt:
  secret: mySecretSignature
  expiration: 604800
  header: X-Auth-Token

